- src/app/components/faqs/FAQs.js
- src/app/components/faqs/FAQs.json
- updated the FAQ section
- included a question regarding MLH 's Code of Conduct
- linked MLH's Code of Conduct
> updated FAQ and MLH Code of Conduct

- src/App.js
- src/app/components/floating-hat/FloatingHat.js
- src/app/components/nav/Nav.js
- src/app/views/home/Home.js
Helps make the site more accessibile for those with vision impairments.
Also removes unused imports.
> Address jsx-a11y warnings

- public/index.html
- src/app/components/nav/Nav.scss
- added mlh logo
- moved nav bar a bit to the left
> added mlh logo

- src/App.js
Taking down the schedule route until we finish the page
> Remove schedule route

- src/app/views/home/Home.js
- src/app/views/home/Home.scss
- font size increases when cursor hover button text
> button animation when hover

- src/App.js
- src/App.scss
- src/app/components/footer/Footer.scss
- src/app/components/index.js
- src/app/components/nav/Nav.js
- src/app/components/tooltip/tooltip.js
- src/app/components/tooltip/tooltip.scss
- src/app/views/home/Home.scss
- src/app/views/index.js
- src/app/views/starter-packs/StarterPacks.js
- src/app/views/starter-packs/StarterPacks.scss
- src/assets/data/starter-pack-info.js
This brings over the starter packs page from HackUCI.
The route has been added to the nav bar.
We'll need to go through and update assets/data/starter-pack-info.js with our starter packs.
Starts #28
> Create /starter-packs page

- package.json
> Fix typo in error message

- src/app/components/meet-team/team.scss
- src/app/components/speakers/keynote.scss
- src/app/components/speakers/panelistfirstrow.scss
- src/app/components/speakers/panelistsecondrow.scss
- src/app/views/home/Home.scss
> fix sponsors and speakers to mobile

- public/index.html
- src/app/components/nav/Nav.js
- src/app/components/nav/Nav.scss
- We now have a mobile nav bar :)
- Moved links to left, brought mlh banner into react
- Add gradient background to make links more visible
Closes #67
> Add Mobile Nav Bar and Nav background

- src/app/components/meet-team/team.scss
- src/app/components/speakers/keynote.scss
- src/app/components/speakers/panelistfirstrow.js
- src/app/components/speakers/panelistsecondrow.js
- add space before panelist subheader
- changed ekaterina's company to cosmos pics
- add margin below meet the team section
> fix panelists section

- package-lock.json
- src/app/components/workshop-card/workshop-card.js
- src/app/components/workshop-card/workshop-card.scss
- src/assets/data/workshops-info.js
- added all the workshop descriptions
- added prerequisites
> ap wrkshpinfo

- src/app/components/workshop-card/workshop-card.js
- src/assets/data/workshops-info.js
Recording will remain hidden until data is provided for it from workshops-info.js
Changed links to open in new tab
> Hide "Recording" link unless it's available

- src/assets/data/starter-pack-info.js
- Rename "User Interface" to "Frontend"
- Move ReactJS to Frontend
- Add React Native and Flutter to Mobile
- Add PeterPortal API to Backend
> Update starter packs

- src/assets/data/starter-pack-info.js
- src/assets/data/workshops-info.js
- added firebase video to starter packs page
- added percentage project video in workshops page
> add firebase and percentage project

- src/assets/data/workshops-info.js
- added starter code to ios dev workshop
> add starter code

- src/App.js
- src/app/views/index.js
- src/app/views/not-found/NotFound.js
- src/app/views/not-found/NotFound.scss
thought this should exist; *should* work fine with gh-pages reroute.
feel free to restyle or add a new background.
> created 404 not found page

- src/App.js
- src/app/views/index.js
- src/app/views/not-found/NotFound.js
- src/app/views/not-found/NotFound.scss
> Add 404 Page

- src/assets/data/workshops-info.js
- added recording for vgdc's workshop
> update with vgdc recap

- src/assets/data/workshops-info.js
- added recording for icssc graphql workshop
> add recap for icssc graphql workshop

- src/assets/data/workshops-info.js
- added slides and video for AI@UCI workshop
> added ai at uci's recap video

- src/assets/data/workshops-info.js
- added recap video and slides for swe's imposter workshop
> added swe recap

- src/assets/data/workshops-info.js
- added recap video and slide for maiss workshop
> maiss workshop

- src/App.js
- src/app/components/nav/Nav.js
Removed 'Schedule', 'Stater Packs', and 'Workshop' routes. Also deleted from navbar.
Ran website through localhost to check if 'Schedule', 'Starter Packs', and 'Workshop' were removed.
Closes #124
> Removed schedule, starter packs, workshop routes.

- src/app/components/footer/Footer.scss
- src/app/components/nav/Nav.scss
- src/globals/zothacks-styles.scss
Changed colors of gradient background, navbar, and footer to match VH 2022 theme.
Closes #143
> Change colors of background, navbar, and footer to match theme

- src/app/components/faqs/FAQs.json
- src/app/components/footer/Footer.scss
- src/app/components/nav/Nav.scss
- src/globals/zothacks-styles.scss
Updated FAQ relative to VH 2022 guidelines and logistics.
Closes #127 
Need to update FAQ regarding application release once we fully launch VH. Some logistics might change as well so will update accordingly.
> Update FAQ 

- src/app/views/home/Home.scss
Hid the speakers section
Closes #125 
Once we know who the speakers are, we'll add that info in
> hid speakers section

- src/app/components/faqs/FAQs.scss
- src/app/components/footer/Footer.scss
- src/app/components/nav/Nav.scss
- src/globals/zothacks-styles.scss
Changed colors (again) to match web accessibility standards. 
idk what im doing 👍🏼
> Change colors (again)

- src/app/components/meet-team/team.js
Fixed Shalini's and Pham's name
Ran locally.
Closes #163
> Updated Shalini's and Pham's name

- src/app/views/home/Home.js
- src/app/views/home/Home.scss
made devpost button visible, changed to "Apply as a Hacker," changed link to "https://airtable.com/shr1Etr4Typ3FEqBc", had the url open in a new tab.
clicking on button should open to a new tab of link used above.
Closes hacker app for #157
> Added Hacker App Button

- src/app/views/home/Home.scss
Changed button text color to fit web accessibility standards: https://webaim.org/resources/contrastchecker/
Ran locally.
Closes #167
> Changed button text color

- src/app/components/faqs/FAQs.json
Add application due date to the FAQ
> Add application due date

- src/app/components/index.js
- src/app/components/venus-button/venusButton.js
- src/app/views/home/Home.js
- src/app/views/home/Home.scss
Created mentor app button, which will redirect to [mentor applications](https://airtable.com/shr5Y9x5ocJaJL52j), and reapplied button hovering when hovering over the buttons so that it'll pop out a bit (or idk how to describe it)
Closes #157 and #172
> Created Mentor App Button and Applied Button Hovering

- src/app/components/faqs/FAQs.json
Added two new FAQs regarding international students and attending in-person.
**Question**: Can international students participate?
**Answer**: VenusHacks is limited to hackers within the United States.
**Question**: Can I attend in-person?
**Answer**: In-person attendance is limited to only official UCI students with proper UCI identification. However, anyone can attend virtually!
Closes #175
Adjust responses if need to be more specific or formatting/order of questions
> Added new FAQs

- src/app/components/footer/Footer.js
- src/app/views/home/Home.js
Changed email addresses:
- "venushacks.corporate@gmail.com" to "sponsorships@venushacks.com" under Past Sponsors section
- "venushacks@gmail.com" to "contact@venushacks.com" under FAQs and on the email icon in footer
Ran with npm start, tested the mailto: fields
Closes #171
> changed emails to venushacks.com domain

- src/app/views/home/Home.js
Hid mentor app button by commenting out line that applies mentor app button
Closes #183
> Hid Mentor App Button

- src/app/views/home/Home.js
Deleted hacker app button since apps closed
N/A
> Hid Hacker App Button

- .github/workflows/test-deploy.yml
- README.md
On a new pull request, this attempts to build the project. 
If there are any warnings, the build check will fail and notify the PR author.
> Check that pull requests successfully build

- src/App.js
- src/app/components/nav/Nav.js
- src/app/components/schedule-card/ScheduleCard.js
- src/app/components/schedule-card/ScheduleCard.scss
- src/app/views/schedule/Schedule.js
- src/assets/data/schedule-info.js
- src/assets/data/workshops-info.js
Added schedule route, updated schedule with information from event [descriptions](https://docs.google.com/document/d/1C9ZrVA1fua9CAlH1NjMUKZv5WumOhatmI-K_as6Txis/edit) and [timeline](https://docs.google.com/spreadsheets/d/1COLZdyU7XeenRDFKCBEN9xGJJeRYH3DdYQGU_gH9seg/edit#gid=1753981004).
- Check route is clickable and routes correctly
- Schedule is listed with required information
- Zoom location redirect to respective Zoom links
Closes #184
Once rest of event timeline and description is finalized, push new changes with updates.
> Added Schedule

- src/App.js
- src/app/components/nav/Nav.js
Added route to form link at "/report" in App.js
Added "Incident Form" button in Nav.js that links to "/report", redirects to form
Ran npm start. Clicking "Incident Form" button navigates to "localhost:3000/report", which redirects to Google Form.
Navigating directly to "localhost:3000/report" also redirects to Google Form.
Closes #198
> Form route

- src/assets/data/resources-info.js
Remove Figma from the resources page
> Remove figma

- src/app/views/home/Home.scss
Headers were either too large or too small. Resized images to appear uniform. Edited the height fields in Home.scss.
Tested locally and resized window to check that headers look similar in size.
Closes #206
> resize headers

- src/app/views/home/Home.js
Title
Clicked WICYS under Partners to see if it redirects to correct link
Closes #209
> Updated link to WICYS

- src/assets/data/schedule-info.js
Saturday Event's locations in 4011 is changed to 3011 due to audio issue in 4011.
Replaced 3011 with 4011 in locations.
Closes #211
> Updated Saturday Events' Locations

- src/assets/data/schedule-info.js
Update API location to remove "DBH 3011"
> Update API Workshop location

- src/app/views/home/Home.js
Added DevPost Button onto Home Page
- Made sure clicking on link redirects to devpost
Closes #214
> Added DevPost Button

- package-lock.json
- public/index.html
- src/App.scss
- src/app/components/faqs/FAQs.json
- src/app/components/faqs/FAQs.scss
- src/app/components/floating-hat/FloatingHat.scss
- src/app/components/footer/Footer.scss
- src/app/components/meet-team/team.scss
- src/app/components/nav/Nav.js
- src/app/components/nav/Nav.scss
- src/app/components/schedule-card/ScheduleCard.scss
- src/app/components/speakers/speakers.scss
- src/app/components/workshop-card/workshop-card.scss
- src/app/containers/numbers-group/NumbersGroup.scss
- src/app/views/home/Home.js
- src/app/views/home/Home.scss
- src/app/views/resources/Resources.scss
- src/app/views/schedule/Schedule.js
- src/app/views/schedule/Schedule.scss
- src/app/views/workshops/Workshops.scss
- src/globals/vh-styles.scss
Updates the VenusHacks website in prep for VH 2023!
Updated homepage, with updated About/FAQs & color theme
> 2/24 Updates

- src/app/components/nav/Nav.js
- src/app/components/nav/Nav.scss
- src/assets/data/workshops-info.js
- Added 2023 Workshops
- Check if workshop information are accurate and correct
- Check if prereq links and host link are correct
- Wait as more workshop information gets finalized
- Add route to page on nav
> Workshops Updated for 2023

- next.config.js
- src/app/(main)/(home)/Home.scss
- src/app/(main)/(home)/page.jsx
- src/app/(main)/vh-styles.scss
Add Hacker, Volunteer, and Mentor applications to the 2024 VH site
> Add 2024 VH Applications

- .github/workflows/deploy-preview.yml
- .github/workflows/deploy-prod.yml
- .gitignore
We will use GitHub Actions workflows to automatically deploy to Vercel on pull requests and pushes to `main`
> Add workflows to deploy to Vercel

- index.html
- src/app/components/footer/Footer.jsx
- src/app/components/footer/Footer.scss
- src/app/components/partners/Partners.scss
- src/app/views/home/Home.jsx
- src/app/views/home/Home.scss
- The 2024 footer is similar to the 2023 one except with Facebook replaced by Tiktok
- Fixes the stars background on the homepage on a mobile view
> 2024 Footer and small homepage fix

- src/app/views/home/Home.jsx
- src/app/views/home/Home.scss
- Adds 2024 Tanesha Moody's Closing Speech
- Adds a button that links to the Closing Ceremony Slides
> Add Tanesha Moody's Closing Speech and Closing Ceremony Slides

- src/App.jsx
- src/app/views/coming-soon/ComingSoon.jsx
- src/app/views/coming-soon/ComingSoon.scss
- src/app/views/index.js
add blank coming soon page and component under src > app > views > coming-soon. exported route in index.js to include ComingSoon component. Updated App.jsx to only have ComingSoon component and not-found.
> Add blank Coming Soon page

- src/App.jsx
- src/app/components/coming-soon-form/ComingSoonForm.jsx
- src/app/components/coming-soon-form/ComingSoonForm.scss
- src/app/components/primary-button/PrimaryButton.jsx
- src/app/components/primary-button/PrimaryButton.scss
- src/app/views/coming-soon/ComingSoon.jsx
- src/app/views/coming-soon/ComingSoon.scss
- src/globals/vh-styles.scss
- Added Mailchimp mailing list
- Created `PrimaryButton` component
- Added back `Nav`
- Add your email to the mailing list
- Ensure you receive a confirmation email
- Ensure you are added to the mailing list after confirming
- I can remove you from the mailing list after testing, just let me know
- Also ensure form resizes for different window sizes
> [Coming Soon] Mailchimp Integration

- site/index.html
- site/package.json
- site/pnpm-lock.yaml
- site/src/app/components/about/About.scss
- site/src/app/components/coral-parallax-section/CoralParallaxSection.scss
- site/src/app/components/faqs/FAQs.scss
- site/src/app/components/floating-laptop/FloatingLaptop.scss
- site/src/app/components/footer/Footer.scss
- site/src/app/components/meet-team/team.scss
- site/src/app/components/nav/Nav.scss
- site/src/app/components/partners/Partners.scss
- site/src/app/components/schedule-card/ScheduleCard.scss
- site/src/app/components/speakers/speakers.scss
- site/src/app/components/sponsors/Sponsors.scss
- site/src/app/components/workshop-card/workshop-card.scss
- site/src/app/views/home/Home.scss
- site/src/app/views/resources/Resources.scss
- site/src/app/views/schedule/Schedule.scss
- site/src/app/views/workshops/Workshops.scss
- site/src/globals/vh-styles.scss
- site/src/index.css
PR for misc tasks including fixing import sass deprecation warning, removing unused images in CoralParallaxSection.scss, changing FAQ line to white, adding space between otter and text in about section, and (attempting) to fix black flicker on page load.
> misc tasks

- sanity/schemaTypes/event.ts
- site/src/app/components/schedule-card/ScheduleCard.jsx
- site/src/app/components/schedule-card/ScheduleCard.scss
- site/src/app/components/schedule-card/getSchedule.ts
- site/src/app/views/schedule/Schedule.jsx
- site/src/app/views/schedule/Schedule.scss
- Added location under the event title. This is an optional variable.
- Renamed bubble inside schedule page to schedule-bubble because having the same variable name as the bubbles in partner section caused it to disappear.
> Event Locations for Schedule Page

- site/src/app/components/hero/HeroTitle.jsx
- site/src/app/components/nav/Nav.jsx
- site/src/app/components/primary-button/PrimaryButton.jsx
- site/src/app/components/primary-button/PrimaryButton.scss
- Created disabled class in `PrimaryButton.scss`
- Created disabled prop for `PrimaryButton.jsx`
- Disabled Apply Primary Button in `HeroTitle.jsx` and changed text
Note: merge main into staging once this PR is merged
> Remove Apply Button
